---
 - hosts: ubuntu
   become: true
   tasks:

   - name: Install python3
     apt: 
	name: python3

   - name: Install pip3
     apt:
	name: python3-pip

   - name: Set pip3 as default pip
     copy:
	src: /usr/bin/pip3
	dest: /usr/bin/pip

   - name: Set python3 as default python


   - name: Install Java open-jdk
     apt:
	name: openjdk-8-jdk

   - name: Install MariaDB
     apt:
	name: mariadb-server

   - name: Start MariaDB
     command: ./mariadb start
     args:
	chdir: 

   - name: Create a database, a table, and input record in MariaDB


   - name: Create MOTD


   - name: Create a user

